const Data = [
  {
    id: 1,
    text: 'All',
    picture: require('../aseets/Vector1.png'),
    screen: 'History',
  },
  {
    id: 2,
    text: 'Shopping',
    picture: require('../aseets/Vector2.png'),
    screen: 'History',
  },
  {
    id: 3,
    text: 'Traveling',
    picture: require('../aseets/Vector3.png'),
    screen: 'History',
  },
  {
    id: 4,
    text: 'Utility Bills',
    picture: require('../aseets/Vector4.png'),
    screen: 'History',
  },

  {
    id: 5,
    text: 'Health',
    picture: require('../aseets/Vector5.png'),
    screen: 'History',
  },
  {
    id: 6,
    text: 'Add More',
    picture: require('../aseets/Vector6.png'),
    screen: 'History',
  },
];
const income = [
  {
    id: 1,
    text: 'All',
    picture: require('../aseets/Vector1.png'),
    screen: 'History',
  },

  {
    id: 2,
    text: 'Shopping',
    picture: require('../aseets/Vector2.png'),
    screen: 'History',
  },
  {
    id: 3,
    text: 'Add More',
    picture: require('../aseets/Vector6.png'),
    screen: 'History',
  },
];
const history = [
  {
    id: 0,
    icon: require('../aseets/arrowdown.png'),
    color: 'green',
    cat: 'Income',
    amount: 'Rs.200',
    subcat: 'Salary',
    date: '24/10/1950',
    screen: 'Shopping',
  },
  {
    id: 1,
    icon: require('../aseets/uparrow.png'),
    color: 'red',
    cat: 'Expense',
    amount: 'Rs.200',
    subcat: 'Buy Shoes',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 2,
    icon: require('../aseets/arrowdown.png'),
    color: 'green',
    cat: 'Income',
    amount: 'Rs.200',
    subcat: 'Salary',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 3,
    icon: require('../aseets/uparrow.png'),
    color: 'red',
    cat: 'Expense',
    amount: 'Rs.200',
    subcat: 'Buy Shoes',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 4,
    icon: require('../aseets/arrowdown.png'),
    color: 'green',
    cat: 'Income',
    amount: 'Rs.200',
    subcat: 'Salary',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 5,
    icon: require('../aseets/uparrow.png'),
    cat: 'Expense',
    amount: 'Rs.200',
    subcat: 'Buy Shoes',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 6,
    icon: require('../aseets/arrowdown.png'),
    color: 'green',
    cat: 'Income',
    amount: 'Rs.200',
    subcat: 'Salary',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 7,
    icon: require('../aseets/uparrow.png'),
    cat: 'Expense',
    amount: 'Rs.200',
    subcat: 'Buy Shoes',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 8,
    icon: require('../aseets/arrowdown.png'),
    color: 'green',
    cat: 'Income',
    amount: 'Rs.200',
    subcat: 'Salary',
    date: '24/10/2022',
    screen: 'Shopping',
  },
  {
    id: 9,
    icon: require('../aseets/uparrow.png'),
    cat: 'Expense',
    amount: 'Rs.200',
    subcat: 'Buy Shoes',
    date: '24/10/2022',
    screen: 'Shopping',
  },
];

export {Data, income, history};
